apiVersion: apps/v1
kind: Deployment
metadata: 
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: tionguyen97/admin
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: JWT_KEY
            - name: JWT_EXPIRES
              valueFrom:
                secretKeyRef:
                  name: jwt-expires
                  key: JWT_EXPIRES
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: MYSQL_URL
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-access-key
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret-key
                  key: S3_SECRET_KEY
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: S3_REGION
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: S3_BUCKET_NAME
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: NATS_URL
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: NATS_CLUSTER_ID
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: DB_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: admin-srv
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - name: admin
      protocol: TCP
      port: 5000
      targetPort: 5000