apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: tionguyen97/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: JWT_KEY
            - name: JWT_EXPIRES
              valueFrom:
                secretKeyRef:
                  name: jwt-expires
                  key: JWT_EXPIRES
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: MYSQL_URL
            - name: DB_NAME
              value: db_user
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 5000
      targetPort: 5000