apiVersion: apps/v1
kind: Deployment
metadata: 
  name: movie-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: tionguyen97/movie
          env:
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: MYSQL_URL
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: movie-srv
spec:
  type: ClusterIP
  selector:
    app: movie
  ports:
    - name: movie
      protocol: TCP
      port: 5000
      targetPort: 5000