apiVersion: apps/v1
kind: Deployment
metadata: 
  name: movie-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: tionguyen97/movie
          env:
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: tix-secret
                  key: MYSQL_URL
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: NATS_URL
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: NATS_CLUSTER_ID
            - name: QUEUE_GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: QUEUE_GROUP_MOVIE
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: tix
                  key: DB_MOVIE
---
apiVersion: v1
kind: Service
metadata:
  name: movie-srv
spec:
  type: ClusterIP
  selector:
    app: movie
  ports:
    - name: movie
      protocol: TCP
      port: 5000
      targetPort: 5000